version = 0.1
[default.deploy.parameters]
stack_name = "inventario-app"
resolve_s3 = true
s3_prefix = "inventario-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PostgresUsername=\"postgres\" PostgresPassword=\"1234512345\" PostgresDatabaseName=\"inventarios\""
image_repositories = []